In [1]:
pip install Kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: Kagglehub in c:\users\dell\appdata\roaming\python\python39\site-packages (0.3.13)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (6.0)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (4.64.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (2.28.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from Kagglehub) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->Kagglehub) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (2022.9.14)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->Kagglehub) (3.3)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->Kagglehub) (0.4.5)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
import numpy as np

In [15]:
df=pd.read_csv("C:\\Users\\DELL\\Desktop\\Jouhara\\flights.csv")

C:\Users\DELL\AppData\Local\Temp\ipykernel_7580\2286840613.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:\\Users\\DELL\\Desktop\\Jouhara\\flights.csv")

In [16]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
columns_needed = [
    'AIRLINE',
    'DEPARTURE_DELAY',
    'ARRIVAL_DELAY',
    'DAY_OF_WEEK',
    'SCHEDULED_DEPARTURE',
    'DISTANCE'
]

df_small = df[columns_needed]

In [23]:
df_small

,AIRLINE,DEPARTURE_DELAY,ARRIVAL_DELAY,DAY_OF_WEEK,SCHEDULED_DEPARTURE,DISTANCE
0,AS,-11.0,-22.0,4,5,1448
1,AA,-8.0,-9.0,4,10,2330
2,US,-2.0,5.0,4,20,2296
3,AA,-5.0,-9.0,4,20,2342
4,AS,-1.0,-21.0,4,25,1448
...,...,...,...,...,...,...
5819074,B6,-4.0,-26.0,4,2359,2611
5819075,B6,-4.0,-16.0,4,2359,1617
5819076,B6,-9.0,-8.0,4,2359,1598
5819077,B6,-6.0,-10.0,4,2359,1189
5819078,B6,15.0,2.0,4,2359,1576

In [24]:
df_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 6 columns):
 #   Column               Dtype
---  ------               -----
 0   AIRLINE              object
 1   DEPARTURE_DELAY      float64
 2   ARRIVAL_DELAY        float64
 3   DAY_OF_WEEK          int64
 4   SCHEDULED_DEPARTURE  int64
 5   DISTANCE             int64
dtypes: float64(2), int64(3), object(1)
memory usage: 266.4+ MB

In [25]:
df_small.describe()

,DEPARTURE_DELAY,ARRIVAL_DELAY,DAY_OF_WEEK,SCHEDULED_DEPARTURE,DISTANCE
count,5.732926e+06,5.714008e+06,5.819079e+06,5.819079e+06,5.819079e+06
mean,9.370158e+00,4.407057e+00,3.926941e+00,1.329602e+03,8.223565e+02
std,3.708094e+01,3.927130e+01,1.988845e+00,4.837518e+02,6.077843e+02
min,-8.200000e+01,-8.700000e+01,1.000000e+00,1.000000e+00,2.100000e+01
25%,-5.000000e+00,-1.300000e+01,2.000000e+00,9.170000e+02,3.730000e+02
50%,-2.000000e+00,-5.000000e+00,4.000000e+00,1.325000e+03,6.470000e+02
75%,7.000000e+00,8.000000e+00,6.000000e+00,1.730000e+03,1.062000e+03
max,1.988000e+03,1.971000e+03,7.000000e+00,2.359000e+03,4.983000e+03

In [26]:
df_small.isnull().sum()

AIRLINE                     0
DEPARTURE_DELAY         86153
ARRIVAL_DELAY          105071
DAY_OF_WEEK                 0
SCHEDULED_DEPARTURE         0
DISTANCE                    0
dtype: int64

In [28]:
df_small.isnull().sum().sort_values()

AIRLINE                     0
DAY_OF_WEEK                 0
SCHEDULED_DEPARTURE         0
DISTANCE                    0
DEPARTURE_DELAY         86153
ARRIVAL_DELAY          105071
dtype: int64

In [31]:
#df_small = df_small.fillna(0)
df_small['ARRIVAL_DELAY'] = df_small['ARRIVAL_DELAY'].fillna(df_small['ARRIVAL_DELAY'].mean())
df_small['DEPARTURE_DELAY'] = df_small['DEPARTURE_DELAY'].fillna(df_small['DEPARTURE_DELAY'].mean())

In [32]:
df_small.head()

df_small.tail()

df_small['AIRLINE'].unique()

array(['AS', 'AA', 'US', 'DL', 'NK', 'UA', 'HA', 'B6', 'OO', 'EV', 'MQ',
       'F9', 'WN', 'VX'], dtype=object)

In [34]:
print(df_small['AIRLINE'].value_counts())

print(df_small['DAY_OF_WEEK'].value_counts())

WN    1261855
DL     875881
AA     725984
OO     588353
EV     571977
UA     515723
MQ     294632
B6     267048
US     198715
AS     172521
NK     117379
F9      90836
HA      76272
VX      61903
Name: AIRLINE, dtype: int64
4    872521
1    865543
5    862209
3    855897
2    844600
7    817764
6    700545
Name: DAY_OF_WEEK, dtype: int64

In [35]:
print("ARRIVAL_DELAY mean",df_small['ARRIVAL_DELAY'].mean())
print("DEPARTURE_DELAY mean",df_small['DEPARTURE_DELAY'].mean())
print("ARRIVAL_DELAY mean",df_small.groupby('AIRLINE')['ARRIVAL_DELAY'].mean())

ARRIVAL_DELAY mean 4.32748223559089
DEPARTURE_DELAY mean 9.231430609551786
ARRIVAL_DELAY mean AIRLINE
AA     3.389336
AS    -0.970438
B6     6.552680
DL     0.185558
EV     6.387061
F9    12.402010
HA     2.016966
MQ     6.110663
NK    14.202285
OO     5.731005
UA     5.347749
US     3.622429
VX     4.687576
WN     4.307522
Name: ARRIVAL_DELAY, dtype: float64